// Catalogo de codigos de erro da aplicacao, usados nas respostas padronizadas.
export const CodigoDeErro = {
  REQUISICAO_INVALIDA: "REQUISICAO_INVALIDA",

  ERRO_DE_VALIDACAO: "ERRO_DE_VALIDACAO",

  NAO_AUTORIZADO: "NAO_AUTORIZADO",

  PROIBIDO: "PROIBIDO",

  NAO_ENCONTRADO: "NAO_ENCONTRADO",

  CONFLITO: "CONFLITO",

  NAO_IMPLEMENTADO: "NAO_IMPLEMENTADO",

  ERRO_INTERNO: "ERRO_INTERNO",

  TOKEN_EXPIRADO: "TOKEN_EXPIRADO",

  TOKEN_INVALIDO: "TOKEN_INVALIDO",

  VERIFICACAO_TOKEN_FALHOU: "VERIFICACAO_TOKEN_FALHOU",

  NENHUM_TOKEN_FORNECIDO: "NENHUM_TOKEN_FORNECIDO",

  CONTA_DESATIVADA: "CONTA_DESATIVADA",

  CADASTRO_EM_ANALISE: "CADASTRO_EM_ANALISE",

  CADASTRO_RECUSADO: "CADASTRO_RECUSADO",

  ERRO_TENTATIVA: "ERRO_TENTATIVA",

  ERRO_FEEDBACK: "ERRO_FEEDBACK",

  TEMAS_NAO_ENCONTRADOS: "TEMAS_NAO_ENCONTRADOS",

  RECURSO_NAO_ENCONTRADO: "RECURSO_NAO_ENCONTRADO",

  SERVICO_INDISPONIVEL: "SERVICO_INDISPONIVEL",
  
} as const;

// Uniao dos valores possiveis de codigo de erro (derivada do objeto acima).
export type ValorCodigoDeErro = (typeof CodigoDeErro)[keyof typeof CodigoDeErro];
