sonar.projectKey=fga-eps-mds_2026-2-AnatoQuizUp-Quiz-Service
sonar.organization=fga-eps-mds-1

sonar.sources=src
sonar.tests=tests,src
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/migrations/**,**/seeds/**,**/*.config.js,**/*.config.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.*,**/*.spec.*,**/*.d.ts,**/index.*,**/server.*,**/migrations/**,**/seeds/**,**/*.config.*,src/scripts/**,src/config/app.ts,src/config/db.ts,src/config/logger.ts,**/*.routes.ts,**/*.constants.ts,**/dto/registrar.*.types.ts,**/dto/resposta.localidade.types.ts,**/dto/resposta.nacionalidade.types.ts,**/dto/resposta.opcoes-academicas.types.ts,src/shared/constants/**,src/shared/types/**,src/shared/errors/**,src/modules/exemplo/**,src/shared/middlewares/papeis.middleware.ts,src/shared/middlewares/tratamento-erros.middleware.ts
sonar.sourceEncoding=UTF-8
